using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Item : MonoBehaviour
{
    public enum EItem
    {
        Strong,
        Shild,
        Repair,
        Fuel,
        Score,
    }
    public EItem eItem;

    [Header("РЬЕП")]
    [SerializeField] int moveSpeed = 0;
    [SerializeField] Vector3 moveDirection = Vector3.zero;

    Player player;

    void Start()
    {
        player = Player.instance;
    }

    void Update()
    {
        Move();
    }

    void Move()
    {
        transform.position += moveSpeed * moveDirection * Time.deltaTime;
    }

    private void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.CompareTag("Player"))
        {
            switch (eItem)
            {
                case EItem.Strong: // ЗЙКЇОї СѕАЁ ОЦРЬХл
                    if (GameManager.instance.currentLevel < 4)
                    {
                        GameManager.instance.currentLevel++;
                    }
                    else
                        GameManager.instance.currentScore += 300;
                    break;

                case EItem.Shild: // ЙцОю ОЦРЬХл
                    break;

                case EItem.Repair: // ГЛБИЕЕ МіИЎ ОЦРЬХл
                    if (player.currentHp + 20 <= player.maxHp)
                        player.currentHp += 20;
                    else
                        player.currentHp = player.maxHp;
                    break;

                case EItem.Fuel: // ПЌЗс СѕАЁ ОЦРЬХл
                    if (player.currentFuel + 30 <= player.maxFuel)
                        player.currentFuel += 30;
                    else
                        player.currentFuel = player.maxFuel;
                    break;

                case EItem.Score: // СЁМі СѕАЁ ОЦРЬХл
                    GameManager.instance.currentScore += 500;
                    break;
            }

            Destroy(gameObject);
        }

        if (collision.gameObject.CompareTag("DestroyWall"))
            Destroy(gameObject);
    }
}
